target 'PreferenceCenterSample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PreferenceCenterSample
  pod 'UrbanAirship-iOS-Tag-Preference-Center', :path => '..'
  pod 'UrbanAirship-iOS-SDK', '~> 8.5.1'

  target 'PreferenceCenterSampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PreferenceCenterSampleUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
